services:
    installer.install_data.add_bots:
        class: phpbb\install\module\install_data\task\add_bots
        arguments:
            - '@installer.helper.config'
            - '@installer.helper.iohandler'
            - '@installer.helper.container_factory'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: install_data_install, order: 20 }

    installer.install_data.add_languages:
        class: phpbb\install\module\install_data\task\add_languages
        arguments:
            - '@installer.helper.iohandler'
            - '@installer.helper.container_factory'
            - '@language.helper.language_file'
        tags:
            - { name: install_data_install, order: 10 }

    installer.install_data.add_modules:
        class: phpbb\install\module\install_data\task\add_modules
        arguments:
            - '@installer.helper.config'
            - '@installer.helper.iohandler'
            - '@installer.helper.container_factory'
        tags:
            - { name: install_data_install, order: 30 }

    installer.install_data.create_search_index:
        class: phpbb\install\module\install_data\task\create_search_index
        arguments:
            - '@config'
            - '@installer.helper.container_factory'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: install_data_install, order: 40 }

    installer.module.data_install_collection:
        class: phpbb\di\ordered_service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: install_data_install, class_name_aware: true }

    installer.module.data_install:
        class: phpbb\install\module\install_data\module
        parent: installer.module_base
        arguments:
            - '@installer.module.data_install_collection'
        tags:
            - { name: installer_install_module, order: 50 }
