services:
    installer.obtain_data.obtain_admin_data:
        class: phpbb\install\module\obtain_data\task\obtain_admin_data
        arguments:
            - @installer.helper.config
            - @installer.helper.iohandler

    installer.obtain_data.obtain_board_data:
        class: phpbb\install\module\obtain_data\task\obtain_board_data
        arguments:
            - @installer.helper.config
            - @installer.helper.iohandler
            - @language.helper.language_file

    installer.obtain_data.obtain_database_data:
        class: phpbb\install\module\obtain_data\task\obtain_database_data
        arguments:
            - @installer.helper.database
            - @installer.helper.config
            - @installer.helper.iohandler

    installer.obtain_data.obtain_email_data:
        class: phpbb\install\module\obtain_data\task\obtain_email_data
        arguments:
            - @installer.helper.config
            - @installer.helper.iohandler

    installer.obtain_data.obtain_imagick_path:
        class: phpbb\install\module\obtain_data\task\obtain_imagick_path
        arguments:
            - @installer.helper.config

    installer.obtain_data.obtain_server_data:
        class: phpbb\install\module\obtain_data\task\obtain_server_data
        arguments:
            - @installer.helper.config
            - @installer.helper.iohandler

    installer.module.obtain_data_install:
        class: phpbb\install\module\obtain_data\module
        parent: installer.module_base
        arguments:
            - ["installer.obtain_data.obtain_admin_data", "installer.obtain_data.obtain_database_data", "installer.obtain_data.obtain_server_data", "installer.obtain_data.obtain_email_data", "installer.obtain_data.obtain_board_data", "installer.obtain_data.obtain_imagick_path"]
            - true
            - false
