services:
    installer.requirements.check_filesystem:
        class: phpbb\install\module\requirements\task\check_filesystem
        arguments:
            - @filesystem
            - @installer.helper.iohandler
            - %core.root_path%
            - %core.php_ext%

    installer.requirements.check_server_environment:
        class: phpbb\install\module\requirements\task\check_server_environment
        arguments:
            - @installer.helper.database
            - @installer.helper.iohandler

    installer.module.requirements_install:
        class: phpbb\install\module\requirements\module
        parent: installer.module_base
        arguments:
            - ["installer.requirements.check_filesystem", "installer.requirements.check_server_environment"]
            - true
            - false
