services:
    avatar.driver.gravatar:
        class: phpbb_avatar_driver_gravatar
        arguments:
            - @config
            - %core.root_path%
            - .%core.php_ext%
            - @cache.driver
        calls:
            - [set_name, [avatar.driver.gravatar]]
        tags:
            - { name: avatar.driver }

    avatar.driver.local:
        class: phpbb_avatar_driver_local
        arguments:
            - @config
            - %core.root_path%
            - .%core.php_ext%
            - @cache.driver
        calls:
            - [set_name, [avatar.driver.local]]
        tags:
            - { name: avatar.driver }

    avatar.driver.remote:
        class: phpbb_avatar_driver_remote
        arguments:
            - @config
            - %core.root_path%
            - .%core.php_ext%
            - @cache.driver
        calls:
            - [set_name, [avatar.driver.remote]]
        tags:
            - { name: avatar.driver }

    avatar.driver.upload:
        class: phpbb_avatar_driver_upload
        arguments:
            - @config
            - %core.root_path%
            - .%core.php_ext%
            - @cache.driver
        calls:
            - [set_name, [avatar.driver.upload]]
        tags:
            - { name: avatar.driver }

    avatar.driver_collection:
        class: phpbb_di_service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: avatar.driver }
