services:
    captchas.factory:
        class: phpbb\captcha\factory
        arguments:
            - @service_container
            - @captchas.plugins.service_collection

    captchas.plugins.service_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: captchas.plugins }

    core.captcha.plugins.gd:
        class: phpbb\captcha\plugins\gd
        scope: prototype # scope MUST be prototype for this to work!
        tags:
            - { name: captchas.plugins }

    core.captcha.plugins.gd_wave:
        class: phpbb\captcha\plugins\gd_wave
        scope: prototype # scope MUST be prototype for this to work!
        tags:
            - { name: captchas.plugins }

    core.captcha.plugins.nogd:
        class: phpbb\captcha\plugins\nogd
        scope: prototype # scope MUST be prototype for this to work!
        tags:
            - { name: captchas.plugins }

    core.captcha.plugins.qa:
        class: phpbb\captcha\plugins\qa
        scope: prototype # scope MUST be prototype for this to work!
        tags:
            - { name: captchas.plugins }

    core.captcha.plugins.recaptcha:
        class: phpbb\captcha\plugins\recaptcha
        scope: prototype # scope MUST be prototype for this to work!
        tags:
            - { name: captchas.plugins }
