services:
    console.command.cache.purge:
        class: phpbb\console\command\cache\purge
        arguments:
            - @cache.driver
            - @dbal.conn
            - @auth
            - @log
            - @user
            - @config
        tags:
            - { name: console.command }

    console.command.config.delete:
        class: phpbb\console\command\config\delete
        arguments:
            - @config
        tags:
            - { name: console.command }

    console.command.config.increment:
        class: phpbb\console\command\config\increment
        arguments:
            - @config
        tags:
            - { name: console.command }

    console.command.config.get:
        class: phpbb\console\command\config\get
        arguments:
            - @config
        tags:
            - { name: console.command }

    console.command.config.set:
        class: phpbb\console\command\config\set
        arguments:
            - @config
        tags:
            - { name: console.command }

    console.command.config.set_atomic:
        class: phpbb\console\command\config\set_atomic
        arguments:
            - @config
        tags:
            - { name: console.command }

    console.command.cron.list:
        class: phpbb\console\command\cron\cron_list
        arguments:
            - @cron.manager
            - @user
        tags:
            - { name: console.command }

    console.command.cron.run:
        class: phpbb\console\command\cron\run
        arguments:
            - @cron.manager
            - @cron.lock_db
            - @user
        tags:
            - { name: console.command }

    console.command.db.migrate:
        class: phpbb\console\command\db\migrate
        arguments:
            - @migrator
            - @ext.manager
            - @config
            - @cache
            - @log
            - @user
        tags:
            - { name: console.command }

    console.command.dev.migration_tips:
        class: phpbb\console\command\dev\migration_tips
        arguments:
            - @ext.manager
        tags:
            - { name: console.command }

    console.command.extension.disable:
        class: phpbb\console\command\extension\disable
        arguments:
            - @ext.manager
            - @log
        tags:
            - { name: console.command }

    console.command.extension.enable:
        class: phpbb\console\command\extension\enable
        arguments:
            - @ext.manager
            - @log
        tags:
            - { name: console.command }

    console.command.extension.purge:
        class: phpbb\console\command\extension\purge
        arguments:
            - @ext.manager
            - @log
        tags:
            - { name: console.command }

    console.command.extension.show:
        class: phpbb\console\command\extension\show
        arguments:
            - @ext.manager
            - @log
        tags:
            - { name: console.command }

    console.command.fixup.recalculate_email_hash:
        class: phpbb\console\command\fixup\recalculate_email_hash
        arguments:
            - @dbal.conn
        tags:
            - { name: console.command }
