parameters:
    core.table_prefix: phpbb_
    cache.driver.class: phpbb_cache_driver_file
    dbal.driver.class: dbal_mysqli
    dbal.dbhost:
    dbal.dbuser: root
    dbal.dbpasswd:
    dbal.dbname: phpbb_dev
    dbal.dbport:
    dbal.new_link: false
    tables.config: %core.table_prefix%config
    tables.ext: %core.table_prefix%ext
