parameters:
    passwords.algorithms:
        - passwords.driver.bcrypt_2y
        - passwords.driver.bcrypt
        - passwords.driver.salted_md5
        - passwords.driver.phpass

services:
    passwords.driver.bcrypt:
        class: phpbb\passwords\driver\bcrypt
        arguments:
            - @config
            - @passwords.driver_helper
        calls:
            - [set_name, [passwords.driver.bcrypt]]
        tags:
            - { name: passwords.driver }

    passwords.driver.bcrypt_2y:
        class: phpbb\passwords\driver\bcrypt_2y
        arguments:
            - @config
            - @passwords.driver_helper
        calls:
            - [set_name, [passwords.driver.bcrypt_2y]]
        tags:
            - { name: passwords.driver }

    passwords.driver.salted_md5:
        class: phpbb\passwords\driver\salted_md5
        arguments:
            - @config
            - @passwords.driver_helper
        calls:
            - [set_name, [passwords.driver.salted_md5]]
        tags:
            - { name: passwords.driver }

    passwords.driver.phpass:
        class: phpbb\passwords\driver\phpass
        arguments:
            - @config
            - @passwords.driver_helper
        calls:
            - [set_name, [passwords.driver.phpass]]
        tags:
            - { name: passwords.driver }

    passwords.driver_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: passwords.driver }

    passwords.driver_helper:
        class: phpbb\passwords\driver\helper
        arguments:
            - @config

    passwords.manager:
        class: phpbb\passwords\manager
        arguments:
            - @config
            - @passwords.driver_collection
            - @passwords.helper
            - %passwords.algorithms%

    passwords.helper:
        class: phpbb\passwords\helper
