parameters:
    tables.auth_provider_oauth_token_storage: %core.table_prefix%oauth_tokens
    tables.auth_provider_oauth_account_assoc: %core.table_prefix%oauth_accounts
    tables.captcha_qa_questions: %core.table_prefix%captcha_questions
    tables.captcha_qa_answers: %core.table_prefix%captcha_answers
    tables.captcha_qa_confirm: %core.table_prefix%qa_confirm
    tables.config: %core.table_prefix%config
    tables.config_text: %core.table_prefix%config_text
    tables.ext: %core.table_prefix%ext
    tables.forums: %core.table_prefix%forums
    tables.log: %core.table_prefix%log
    tables.migrations: %core.table_prefix%migrations
    tables.modules: %core.table_prefix%modules
    tables.notification_types: %core.table_prefix%notification_types
    tables.notifications: %core.table_prefix%notifications
    tables.profile_fields: %core.table_prefix%profile_fields
    tables.profile_fields_data: %core.table_prefix%profile_fields_data
    tables.profile_fields_options_language: %core.table_prefix%profile_fields_lang
    tables.profile_fields_language: %core.table_prefix%profile_lang
    tables.posts: %core.table_prefix%posts
    tables.topics: %core.table_prefix%topics
    tables.user_notifications: %core.table_prefix%user_notifications
    tables.users: %core.table_prefix%users
