parameters:
    tables.config: %core.table_prefix%config
    tables.ext: %core.table_prefix%ext
    tables.notifications: %core.table_prefix%notifications
    tables.user_notifications: %core.table_prefix%user_notifications
