parameters:
    tables.auth_provider_oauth: %core.table_prefix%auth_provider_oauth
    tables.config: %core.table_prefix%config
    tables.config_text: %core.table_prefix%config_text
    tables.ext: %core.table_prefix%ext
    tables.forums: %core.table_prefix%forums
    tables.log: %core.table_prefix%log
    tables.migrations: %core.table_prefix%migrations
    tables.modules: %core.table_prefix%modules
    tables.notification_types: %core.table_prefix%notification_types
    tables.notifications: %core.table_prefix%notifications
    tables.posts: %core.table_prefix%posts
    tables.topics: %core.table_prefix%topics
    tables.user_notifications: %core.table_prefix%user_notifications
    tables.users: %core.table_prefix%users
