imports:
    - { resource: ../default/config.yml }

core:
    require_dev_dependencies: true
    allow_install_dir: true

    debug:
        exceptions: true
        load_time: true
        sql_explain: true
        memory: true
        show_errors: true

    twig:
        debug: true
        auto_reload: true
        enable_debug_extension: true

    extensions:
        composer_debug: true
        composer_verbose: true

    session:
        log_errors: true
